services:
  minio-restream:
    image: rust:latest
    volumes:
      - ..:/workspace:cached
      - repos:/repos/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: host
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes: 
      - data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_PASSWORD: testingpass
      MINIO_ROOT_USER: testingpass

volumes:
  repos:
  data: